### ISSUE TITLE
can't pair airplay

### ISSUE THREAD

**Issue by BorussiaPlayer17** [twocolors/node-red-contrib-apple-tv-x#12]
Installed the plugin inside my docker Container. Search and companion pair was successful. But I can't pair airplay. Plugin is unable to connect to my aTV4k. 

`2022-02-22 07:57:08 ERROR [pyatv.scripts.atvremote]: Pairing failed
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyatv/support/__init__.py", line 33, in error_handler
    return await func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyatv/protocols/airplay/auth/hap.py", line 43, in start_pairing
    await self.http.post("/pair-pin-start", headers=_AIRPLAY_HEADERS)
  File "/usr/lib/python3.8/site-packages/pyatv/support/http.py", line 359, in post
    return await self.send_and_receive(
  File "/usr/lib/python3.8/site-packages/pyatv/support/http.py", line 412, in send_and_receive
    raise exceptions.HttpError(
pyatv.exceptions.HttpError: HTTP/1.1 method POST failed with code 400: Bad Request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 179, in pair
    await self._perform_pairing(pairing)
  File "/usr/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 189, in _perform_pairing
    await pairing.begin()
  File "/usr/lib/python3.8/site-packages/pyatv/protocols/airplay/pairing.py", line 62, in begin
    return await error_handler(
  File "/usr/lib/python3.8/site-packages/pyatv/support/__init__.py", line 41, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.PairingError: HTTP/1.1 method POST failed with code 400: Bad Request`

**Comment by twocolors** [comment]
hi, you can try use only "companion". this issues is pyatv mb help @postlund

**Comment by BorussiaPlayer17** [comment]
i already did. The Plugin doesn't connect.

**Comment by postlund** [comment]
This is an AirPlay problem, so companion won't solve that. Did you try restarting the Apple TV for starters?

**Comment by postlund** [comment]
Did you update your AirPlay access setting to allow everyone on the same network? Must be done on the Apple TV.

**Comment by BorussiaPlayer17** [comment]
did restart it. Normaly my atv is set to allow everyone to connect. Will check that today.

**Comment by BorussiaPlayer17** [comment]
Ok, sorry for the delay. You got right @postlund ! The atv was set to allow only members of my home. Changed it to "allow everyone on the same network" and it works. Thanks for the hint. Maybe we should add this to the readme. ;-)

**Comment by twocolors** [comment]
@BorussiaPlayer17 send pull :) @postlund thx
