### ISSUE TITLE
"Error: power_state is not supported"

### ISSUE THREAD

**Issue by Kimovitzh** [twocolors/node-red-contrib-apple-tv-x#17]
Hi

I just installed the node and the pyatv on my raspberry.
My Raspberry and Apple TV is on different LANs but the lan allows crostalk.

This:
```
$ atvremote --id 00:11:22:33:44:54 --protocol companion pair
$ atvremote --id 00:11:22:33:44:54 --protocol airplay pair
```
Doesn't work.

I just get:
`2022-04-23 20:30:45 ERROR [pyatv.scripts.atvremote]: Could not find any Apple TV on current network`

Searching in the node finds the Apple TV, but when I try to inject any payload I just get this:

Error: Got pyatv Error: power_state is not supported

```
pyatv Stacktrace:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyatv/scripts/atvscript.py", line 302, in appstart
    print(args.output(await _handle_command(args, abort_sem, loop)), flush=True)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/scripts/atvscript.py", line 198, in _handle_command
    return await _run_command(atv, args, abort_sem, loop)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/scripts/atvscript.py", line 218, in _run_command
    output(True, values={"power_state": atv.power.power_state.name.lower()})
  File "/usr/local/lib/python3.7/dist-packages/pyatv/support/shield.py", line 72, in _guard_method
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/core/facade.py", line 338, in power_state
    return self.relay("power_state")
  File "/usr/local/lib/python3.7/dist-packages/pyatv/core/relayer.py", line 91, in relay
    target, chain(self._takeover_protocol, priority or self._priorities)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/core/relayer.py", line 114, in _find_instance
    raise exceptions.NotSupportedError(f"{target} is not supported")
pyatv.exceptions.NotSupportedError: power_state is not supported
```

What am I missing?

**Comment by twocolors** [comment]
i see you use apple tv id, try host (ip adress )
